# Generated by Django 4.1.3 on 2023-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
